### ISSUE TITLE
Render AjaxSubmitButton in Gridview

### ISSUE THREAD

**Issue by whmemon** [demogorgorn/yii2-ajax-submit-button#13]
I am facing problem in rendering AjaxSubmitButton in Gridview. 
It should be on location 1 but i comes on location2.

Following is my code.

`[ 
            'format'=>'html',
            'value'=>    function() {
                AjaxSubmitButton::begin([
                    'label' => 'Check',
                    'ajaxOptions' => [
                        'type' => 'POST',
                        'url' => 'country/getinfo',
                        /*'cache' => false,*/
                        'success' => new \yii\web\JsExpression('function(html){
            $("#output").html(html);
            }'),
                    ],
                    'options' => ['type' => 'submit'],
                ]);
                AjaxSubmitButton::end();

        }
],`
![untitled](https://cloud.githubusercontent.com/assets/12655625/22924419/dd09d826-f2c6-11e6-976b-b5cbf4674357.png)

**Comment by demogorgorn** [comment]
Hello! If you want to use this button in Yii2 Grid you should use **return** statement in an anonymous function in the row. Otherwise it doesn't work.

Please notice that this is first of all yii2 ajax **submit** button.

**Comment by demogorgorn** [comment]
for example: 

```
'class' => 'yii\grid\DataColumn', // can be omitted, as it is the default
                'value' => function ($data) {
                    return \demogorgorn\ajax\AjaxSubmitButton::widget([
                        'label' => 'Check',
```
