### ISSUE TITLE
Usage not possible with ActiveForm?

### ISSUE THREAD

**Issue by waza-ari** [demogorgorn/yii2-ajax-submit-button#6]
I am using an active form based on a model and want to submit this via Ajax. The view code basically looks like this:

```php
        <?php $clubForm = ActiveForm::begin([
            'action' => Url::to(['club/ajax-create']),
        ]); ?>

        <?= $clubForm->field($clubModel, 'name')->textInput(['maxlength' => 150]) ?>

        <?= $clubForm->field($clubModel, 'nation')->dropDownList(
            ArrayHelper::map(Nation::find()->all(), 'id', 'name')
        ) ?>

        <div class="form-group">
            <?php AjaxSubmitButton::begin([
                'label' => 'Speichern',
                'id' => 'saveClubButton',
                'ajaxOptions' => [
                    'type' => 'POST',
                    'url' => Url::to(['club/ajax-create']),
                    'success' => new \yii\web\JsExpression('saveCreatedClub(result)'),
                ],
                'options' => ['class' => 'btn btn-success', 'type' => 'submit'],
            ]);
            AjaxSubmitButton::end();
            ?>
        </div>

        <?php ActiveForm::end(); ?>
```

However, pressing the button causes the form to perform a POST request, and the page is reloaded, instead if an AJAX request. (Action is the page where the widget is used).

**Comment by demogorgorn** [comment]
Hello! Why not? I use this button with activeform. Try to delete the form action here:

```php
<?php $clubForm = ActiveForm::begin([
            /*'action' => Url::to(['club/ajax-create']),*/
        ]); ?>
```

also, maybe the server doesn't succeed to make in time the execution of the ajax request?

**Comment by waza-ari** [comment]
Hi! Thank you for your answer. Sorry, the action was only added for testing purposes, the described behaviour also happens if the section is not there.

At the current stage in development, the server is running local on my laptop, and the request is a simple creation of one new database entry - this should not be the issue. For the moment, I just created a button and a few lines of JS myself, and this works - however I will try this extension again and provide further details. I cannot give an exact point in time, though.

**Comment by demogorgorn** [comment]
Now its working with ActiveForm (including client validation)
Please see https://github.com/demogorgorn/yii2-ajax-submit-button/commit/00a41ebd0fd8207fed9f1d6ed79fbfc4b847ae8b
